### ISSUE TITLE
Redirecionamento infinito

### ISSUE THREAD

**Issue by mateuscgc** [InfoJrUFBA/siaej#41]
@InfoJrUFBA/erp-jr 

Pessoal, acredito que isso seja algo incorreto, aconteceu que a session de login estava setada só que não existia o usuário no banco, então o método `require_login` estava dando falso e redirecionando para o root, mas como o id estava na session o routes interpretava para rota de autenticado e isso estava gerando um loop infinito.

A solução que eu pensei foi de tirar o id da session no `require_login` antes de redirecionar para root

O que vocês acham?

**Comment by marcoafilho** [comment]
A gente vai precisar disso, especialmente porque provavelmente quem vai remover o usuário não é ele mesmo e sim um administrador.
