### ISSUE TITLE
Como um membro de DAF eu gostaria de registrar transações

### ISSUE THREAD

**Issue by marcoafilho** [InfoJrUFBA/siaej#5]
Dentro de uma conta eu devo ser capaz de criar transações. Transações possuem:

* Conta;
* Descrição;
* Tipo (Entrada ou saída).
* Data da transação;

**Comment by mateuscgc** [comment]
@InfoJrUFBA/erp-jr 

Pessoal seria o caso de se usar [Resources aninhados](http://guides.rubyonrails.org/routing.html#nested-resources)?

Sempre quis usar esse negoço
